name: ESP32 Build, Test and Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESP-IDF prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Set up ESP-IDF
        run: |
          git clone --branch v5.0 https://github.com/espressif/esp-idf.git ~/esp-idf
          bash ~/esp-idf/install.sh
          echo "source ~/esp-idf/export.sh" >> $GITHUB_ENV

      - name: Build ESP32 firmware
        run: |
          source ~/esp-idf/export.sh
          idf.py build

      - name: Run tests
        run: |
          source ~/esp-idf/export.sh
          # Replace below with your actual test command (e.g., idf.py test, pytest, etc.)
          echo "Running tests..."
          idf.py test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: |
            build/*.bin
            build/*.elf
            build/*.map
